sudo: required
services:
  - docker

before_install:
  - docker build -t gbolahanolawuyi/docker-react -f Dockerfile.dev .

scripts:
  - docker run gbolahanolawuyi/docker-react npm run test -- --coverage
  