language: node_js
services:
  - docker

before_install:
  - docker build -t gbolahanolawuyi/docker-react -f Dockerfile.dev .

script:
  - docker run gbolahanolawuyi/docker-react npm run test -- --coverage
  